name: Webapp CI

on:
  push:
    branches: [ main, reasonops-main-merge ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install
        run: npm ci || npm install

      - name: Test
        run: npx vitest run --reporter=dot

      - name: Build
        run: npm run build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: webapp-dist
          path: webapp/dist
